### ISSUE TITLE
[TODO] For 1.0 Release.

### ISSUE THREAD

**Issue by Rushyanth111** [Rushyanth111/Semester-Stats#36]
- [x] API Routing. A Major Part of this is still left over.
- [x] Common Report Module. A Module to Help Translate over the various Reports to the API.
- [x] Backlog and Detained Calculations.
- [x] Bulk CRUD operation. 
- [x] Report Generation.
- [x] API Testing.
- [x] Integration Testing.
- [x] Document Generation.

**Comment by Rushyanth111** [comment]
ApI Routing is Completed as of the Latest Commit. However, the endpoints such as Detained/Backlog remain unwritten due to there not being a method as of right now.

**Comment by Rushyanth111** [comment]
Common Report Module Over at: https://github.com/Rushyanth111/Semester-Stats-Report

**Comment by Rushyanth111** [comment]
Detained And Backlog Generation are now available.

**Comment by Rushyanth111** [comment]
Document Generation is Completed as of #37

**Comment by Rushyanth111** [comment]
Authentication is Apparently Unneeded, removing.

**Comment by Rushyanth111** [comment]
API Testing and Integration Testing Have been Completed as of #42. Road to 1.0 Has been Finished.
